site_name: Development manual
site_url: http://www.clinicalgenomics.se/development
repo_url: https://github.com/Clinical-Genomics/development
site_author: Team <teamname>

markdown_extensions:
  - footnotes
  - markdown_include.include:
      base_path: docs

theme:
  name: 'readthedocs'
  palette:
    primary: 'blue grey'
    accent: 'cyan'

nav:
  - Home: 'index.md'
#  - Where do I develop?
  - What are the commonly used tools?: 'tools/README.md'
  - Choose a development workflow:
    - Overview: 'dev/models.md'
    - github flow: 'dev/githubflow.md'
    - git flow: 'dev/gitflow.md'
  - 'How do confine my project?':
    - 'How to name your conda env': 'conda/conda_conventions.md'
    - 'How do I activate an env?': 'conda/activate.md'
    - 'How do I manage perl and cpanm?': 'perl/installation/perlbrew.md'
#    - What are the commonly used commands?
  - Choose your editor :): 'editors/README.md'
  - How do we use Python?:
    - conventions: 'python/conventions.md'
    - variables: 'python/variables.md'
    - logging: 'python/logging.md'
#    - CLI
    - 'How to write unit tests?':
      - 'GIVEN-WHEN-THEN': 'python/testing/index.md'
      - 'Are you using fixtures?': 'python/testing/fixtures.md'
#    - How to write documentation?  -
#  - How to run on stage?
#    - How to use databases?
  - How to publish your tool?:
    - How to publish your tool?: 'publish/prod.md'
#    - CHANGELOG
#    - How to make a Python package?
#    - How to bumpversion?
    - How to automate running your tool?: 'publish/crontab.md'
    - How make updating your tool easy?: 'publish/update-scripts.md'
    - Who can sign off on tests, reviews and deploys?: 'publish/sign-off.md'
    - How to update configuration?: 'publish/servers.md'
#  - What are the security concerns?
  - How do we use github?:
    - How to make a pull request?: 'github/pr.md'
    - How to request a pull request review?: 'github/pr-request.md'
    - Pull request etiquette: 'github/pr-etiquette.md'
    - Checklist for a github repository: 'dev/project.md'
  - Other recommendations?:
    - What if I need perl?: perl/README.md
    - What are perl's best practices?: perl/best_practises/best_practises.md
#    - What do we recommend for web develoment?
#  - How do we do project management?
  - How do I publish this manual?: 'mkdocs/index.md'
