site_name: Development manual
site_url: http://www.clinicalgenomics.se/development
repo_url: https://github.com/Clinical-Genomics/development
site_author: Team <teamname>
markdown_extensions:
  - footnotes

theme:
  name: 'readthedocs'
  palette:
    primary: 'blue grey'
    accent: 'cyan'

nav:
  - Home: 'index.md'
#  - Where do I develop?
#    - and what are the commonly used tools? (tmux, …)
#  - 'How do I start a project with git?': 'git/index.md'
  - 'How do confine my project?':
    - 'How to name your conda env': 'conda/conda_conventions.md'
    - 'How do I activate an env?': 'conda/activate.md'
    - 'How do I manage perl and cpanm?': 'perl/installation/perlbrew.md'
#    - What are the commonly used commands?
  - Choose your editor :): 'editors/README.md'
  - How do we use Python?:
    - conventions: 'python/conventions.md'
    - variables: 'python/variables.md'
    - logging: 'python/logging.md'
#    - CLI
    - 'How to write unit tests?':
      - 'GIVEN-WHEN-THEN': 'python/testing/index.md'
      - 'Are you using fixtures?': 'python/testing/fixtures.md'
#    - How to write documentation?  - 
#  - How to run on stage?
#    - How to use databases?
  - How to publish your tool?:
#    - How do we use github for that?
#    - CHANGELOG
#    - How to make a Python package?
#    - How to bumpversion?
    - How to automate running your tool?: 'publish/crontab.md'
    - How make updating your tool easy?: 'publish/update-scripts.md'
    - How to publish your tool?: 'publish/prod.md'
#  - What are the security concerns?
  - Other recommendations?:
    - What if I need perl?: perl/README.md
    - What are perl's best practices?: perl/best_practises/best_practises.md
#    - What do we recommend for web develoment?
#  - How do we do project management?
  - How do I publish this manual?: 'mkdocs/index.md'
